name: Sample Action with Email

on:
  push:
    branches:
      - main  # This triggers the workflow when code is pushed to the 'main' branch.
  workflow_dispatch: # Allows manual triggering from the GitHub UI.

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 23f2005283@ds.study.iitm.ac.in  # Name includes the specified email
        run: echo "Hello, world!"  # The action that runs in this step
